/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createEntryStatsDtoFromDiscriminatorValue, type EntryStatsDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /entries/stats
 */
export interface StatsRequestBuilder extends BaseRequestBuilder<StatsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<EntryStatsDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<EntryStatsDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const StatsRequestBuilderUriTemplate = "{+baseurl}/entries/stats";
/**
 * Metadata for all the requests in the request builder.
 */
export const StatsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: StatsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json, application/json;v=1, application/json;v=2, application/vnd.dev-habit.hateoas+json, application/vnd.dev-habit.hateoas.1+json, application/vnd.dev-habit.hateoas.2+json",
        adapterMethodName: "send",
        responseBodyFactory:  createEntryStatsDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
