//<auto-generated/>
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DevHabit.Api.Migrations.Identity
{
    /// <inheritdoc />
    public partial class Fix_Identity_Table_Names : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "asp_net-user_tokens",
                schema: "identity",
                newName: "asp_net_user_tokens",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net-user_roles",
                schema: "identity",
                newName: "asp_net_user_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net-role_claims",
                schema: "identity",
                newName: "asp_net_role_claims",
                newSchema: "identity");

            migrationBuilder.AlterColumn<string>(
                name: "token",
                schema: "identity",
                table: "refresh_tokens",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(300)",
                oldMaxLength: 300);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.RenameTable(
                name: "asp_net_user_tokens",
                schema: "identity",
                newName: "asp_net-user_tokens",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_user_roles",
                schema: "identity",
                newName: "asp_net-user_roles",
                newSchema: "identity");

            migrationBuilder.RenameTable(
                name: "asp_net_role_claims",
                schema: "identity",
                newName: "asp_net-role_claims",
                newSchema: "identity");

            migrationBuilder.AlterColumn<string>(
                name: "token",
                schema: "identity",
                table: "refresh_tokens",
                type: "character varying(300)",
                maxLength: 300,
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(1000)",
                oldMaxLength: 1000);
        }
    }
}
